version: '3'
services:
    web:
        build: .
        volumes:
            - .:/app
            - ~/.aws/:/root/.aws
            - ~/.gcloud/:/root/.gcloud
        environment:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_PROFILE
            - AWS_SESSION_TOKEN
            - AWS_SECURITY_TOKEN
        command: sleep 365d