version: '3'
services:
    web:
        build: .
        volumes:
            - .:/app
            - ~/.aws/:/root/.aws
            - ~/.gcloud/:/root/.gcloud
        environment:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_PROFILE
            - AWS_SESSION_TOKEN
            - AWS_SECURITY_TOKEN
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        command: sleep 365d
        links:
            - db
    db:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        volumes:
            - /var/lib/postgresql
        ports:
            - "5432:5432"
 